### ISSUE TITLE
我在1月31日时新赞助了50＄，但他并没有转换为nep在游戏里的邮箱中出现

### ISSUE THREAD

**Issue by akbn127** [itsamewayu/OLFallenDoll#1171]
您好，我在1月31日时新赞助了50＄，但他并没有转换为nep在游戏里的邮箱中出现.
![J)2PMCJ190)SW4Y`I0PTCTV](https://github.com/itsamewayu/OLFallenDoll/assets/75793617/741e4173-3b1a-4ade-8015-f7a7fd9fc391)
并且显示已经关联patreon
![@8( 647VXM9VEEIENQ~3YAT](https://github.com/itsamewayu/OLFallenDoll/assets/75793617/b41ec884-6a52-4afa-9b3a-f94a82eb87d3)
我的patreon账号是2502590498@qq.com
steamid是trigger
游戏内id为草海水
![2`I0PXD@RC5VGM7T$}RKXQ5](https://github.com/itsamewayu/OLFallenDoll/assets/75793617/78b9c656-262b-487e-b168-648037971c90)
![M8N3`NEY 84{{DG@8XAL4L2](https://github.com/itsamewayu/OLFallenDoll/assets/75793617/84c3bd50-a25c-423b-97e6-050697ba8488)
这是我的支付记录，望尽快给我答复

**Comment by Awfulwaffle1** [comment]
@akbn127 if you have not already, please make a support ticket in the Operation Lovecraft community discord. We can help there rather than here. The github should be used for game issues and not individual account issues. Please and thank  you

 如果您还没有，请在“洛夫克拉夫特行动”社区不和谐中制作支持票。我们可以在那里提供帮助，而不是在这里。 github 应该用于解决游戏问题，而不是个人帐户问题。谢谢，麻烦您了
