### ISSUE TITLE
[Model] Model flickering

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#211]
How to reproduce: The model flickers in bright yellow lighting in some specific angles. It also happens in gallery mode.

![grafik](https://user-images.githubusercontent.com/79604882/144340371-1d8b1061-11b5-4362-9788-e4ac916ed176.png)

credit leakysigmoid

**Comment by LeakySigmoid** [comment]
![image](https://user-images.githubusercontent.com/95391055/144340953-6d649c68-5e10-4026-9481-8223c567a18c.png)
Also in gallery mode.


Specification:
**PC1(Azure NV6 Virtual Machine)**
CPU: Intel Zeon E5 2690 v3 @ 2.60GHz
GPU: Nvidia Tesla M60

**PC2(Surface Book 2)**
CPU: Intel Core i7 8650U @ 1.90GHz
GPU: Nvidia GTX 1060 6GB

| Flickering | Harem mode | Gallery |
| :---         |     :---      |          :--- |
| PC1 |  flickers  | flickers |
| PC2 | IDK* | flickers |

*: Couldn't launch harem due to anticheat

**Comment by LeakySigmoid** [comment]
Additionally: I assume this happens when the camera is right in front of a light source. (e.g. lamp)
