### ISSUE TITLE
Can't use poses that i researched from other player's

### ISSUE THREAD

**Issue by MrMuppet21** [itsamewayu/OLFallenDoll#440]
**Cant use Poses**

I noticed that i cant use some poses.
I mustly unlocked xeno x human poses.
Then i researched human x human poses from other player's through the like system.
After the 24h wait time i cant use them, i am trying to place them but nothing happens.

 - OS: Win 10
 - Game Version 0.4.5
 - Processor(CPU): Intel Core i7-11700F
 - Graphics Card: RTX 3060
 - Memory: 32 GB

**Comment by johnathandarkly** [comment]
there is no 24 hour wait time for researched experiments. you can use them instantly for up to 24 hours. after 24 hours they are forgotten.... lost to you. 

bug #258 lets you place expired researched experiments, but the bug is you can start to place them. they shouldn't be selectable at all after 24 hours.
