### ISSUE TITLE
[Crashes] Potential reason for causing low fps due to RAM sizes

### ISSUE THREAD

**Issue by mejackwong** [itsamewayu/OLFallenDoll#464]
**Describe the bug**
Computer with 16gb RAM experiencing 100% cpu usage and aroung 30 fps will now have nearly 70 fps after upgrading RAM from 16gb to 32gb and CPU usage is reduced significantly. Tested by a few people.

**To Reproduce**
Use 16gb RAM to test
Then upgrade to 32gb RAM to test again
Other conditions being constant

**Expected behavior**
FPS increases and cpu usage decreases.

**Screenshots**

**Desktop (please complete the following information):**
 - Win10
 - 0.46
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 3700x
 - Graphics Card: rtx3070
 - Memory: 16gb to 32gb

**Additional context**
Hope this helps identifying optimization problem.

**Comment by TheSoulWizard** [comment]
My guess is that low framerates are caused by a bug that causes the CPU to be 100% utilized therefore creating a bottleneck and resulting in low framerates.
There are assumptions that it's caused by the texture streaming engine that tries to store textures in RAM.

I'm guessing that there's a loop on loading and un-loading these textures as the memory gets filled up and tries to makes some space, so, the game **_probably_** tries to load the textures in full resolutions which is roughly ~22 GB (based on my tests) but at the same time, "memory management" clears these textures to free up space in RAM and resulting on extreme CPU load.

Issue #65 could've possibly prevented this problem if that was the case.

There are no official information on what causes the high CPU usage, but trust me, the devs are **very** aware of this issue.
