### ISSUE TITLE
[animation]lesbian scene doesn't work

### ISSUE THREAD

**Issue by nakamura1234a** [itsamewayu/OLFallenDoll#551]
**Describe the bug**
Lesbian scene doesn't work
The inoperable scenes I found are "Crawling back double-headed dildo" and "Standing fingering".

**To Reproduce**
1. Go to 'harem mod', 'Archimedes Orbit Station', '
2. Click on E key.
3. Select the above scene
4. doesn't work

**Expected behavior**
I want to see that scene. One is the most rare scene, so I'm very disappointed.

**Screenshots**
nothing

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.49]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-6700K]
 - Graphics Card:[e.g. GTX 1060]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.
Game doesn't crash

**Additional context**

**Comment by Jorveck** [comment]
Im also having this problem with the Scissoring lesbian scene.  I own it, I can select it, it shows me where to place it, then when I click apply the scene dissapears.

**Comment by johnathandarkly** [comment]
"standing fingering" has been working for me without trouble. i actually own it. 

there is no "crawling back" animation, but there are a few double dildo animations. i don't own them though. i do **see** them in the menu because i've learned them a few times, but i don't actually **own** them. your issue might be related to that, see issue https://github.com/itsamewayu/OLFallenDoll/issues/116
