### ISSUE TITLE
MY ACCOUNT DISAPPEARED

### ISSUE THREAD

**Issue by snk3139** [itsamewayu/OLFallenDoll#635]
**Describe the bug**
My game account disappeared.
“input your username” screen appears when i enter the harem mode.

Just passed “input your username” screen many hours ago, even linked on patreon, and claimed the emails xD

When I input my nickname. the error says
“the ID already exists”

PLEASE Help me to find my patreon-linked account back…

**To Reproduce**
1. Go to 'harem mode'
2. Click on 'nothing'
3. “input your username” screen

**Expected behavior**
lobby, just a lobby with my one and only account

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): ryzen 5600x
 - Graphics Card: RTX 3060
 - Memory: 32GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Referenced a lot of dupe or related issues to this entry. This is currently being addressed. May be related to Patreon API error, but is odd as some of the users that have not attempted to link their account still resulted in receiving the prompt to enter a new user account with their original name being taken. 

Message from Colress in the discord:
Some Reporting "lost" or missing account (needing to recreate an account) after linking your Patreon account, for now I'd advise to not link them if you haven't done so yet. This will be fixed in due time.
