### ISSUE TITLE
Error Code {"code":320000001,"error":"Authentication failed"} When Accessing Harem mode

### ISSUE THREAD

**Issue by ilsingr** [itsamewayu/OLFallenDoll#664]
When I click on harem Mode I receive the error. {"code":320000001,"error":"Authentication failed"} other game modes work normally

**To Reproduce**
1. Go to 'main menu'
2. Click on 'Harem'
3. Scroll down to 'n/a'

**Expected behavior**
To play game in Harem mode

**Screenshots**
<img width="964" alt="OperationLovecraft Harem Error Message" src="https://user-images.githubusercontent.com/128727319/227265801-4a5b3f9a-7eef-45c7-a4a0-5a5cfa8be8d2.png">

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 9 5900HS with Radeon Graphics 3.30 GHz
 - Graphics Card: GeForce RTX
 - Memory: 16GB

*If your game crashed, remember to upload the dmp file with your issue.

**Additional context**

**Comment by LilWaldmensch** [comment]
I get the same issue each time i try to start Harem mode

**Comment by DragonQuestHero** [comment]
same!

**Comment by Wulfric33** [comment]
this happens to me still too

**Comment by sinavskis** [comment]
When I click on harem Mode I receive the error. {"code":320000001,"error":"Authentication failed"} other game modes work normally.

Steps to reproduce the behavior:
- Go to 'main menu'
- Click on 'Harem'
- Scroll down to 'n/a'
- See error
Expected behavior
- To play game in Harem mode

Laptop system information:
OS: Windows 11
Game Version: 0.7.0
Processor(CPU): Intel I7-1200H, 2700 Mhz, 14 cores
Graphics Card: NVIDIA GeForce RTX3070 Ti Laptop GPU
Memory: 16GB

Screenshot:
![Screenshot 2023-03-27 232903](https://user-images.githubusercontent.com/94620629/228072448-e726d690-965c-43de-a32d-450dc55492f4.png)

**Comment by DeathAdrift** [comment]
Processor: AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
Graphics Card: NVIDIA GeForce RTX 3070 Ti
same issue after the update

**Comment by DeathAdrift** [comment]
still same issue after newest update

**Comment by Awfulwaffle1** [comment]
No reports of these issues in discord. Should be resolved by now. Closing.
